### PR TITLE
add checks for programs used and display nicer error messages if they aren't installed

### PR DESCRIPTION
**Pull request by autopulated**
@jaustin @rgrover there's a !!!FIXME because I'm not sure where srec_cat and friends should be installed from for windows/linux?

### CODE REVIEW

**Comment by sg-** [comment]
Can we make / use python equivalents for these and install with yotta via pip?

**Comment by autopulated** [comment]
for srec_cat you probably could, but in general we can't expect people to post-process only with python tools, so this is intended to be an example of how to check for the tools needed to build gracefully, and fail with instructions of where to get them.

**Comment by sg-** [comment]
What example did you have in mind that you could not use python for?

**Comment by autopulated** [comment]
I don't have a specific example in mind.

**Comment by sg-** [comment]
Thanks! Just pointing this out as a long standing deficiency in mbed exporters and it would be nice to elegantly solve these problems rather than keep on kicking the bucket - especially when trivial to solve.

**Comment by autopulated** [comment]
Just a heads up that I think some of the variables need quotes in case there are spaces in them. Don't merge yet!

**Comment by bridadan** [comment]
I went ahead and did this for the nrf51822-gcc target in #9. Please leave comments!

**Comment by autopulated** [comment]
aborting this in favour of #9

**Pull request closed without merging**
