### PR TITLE
renaming Nordic softdevice license agreement

### PR DESCRIPTION
**Pull request by rgrover**
Based on Jilayne's email.

@aewp2

### CODE REVIEW

**Comment by aewp2** [comment]
Hi Rohit
I don't know what magic you're pulling off here but it looks like changing the name of this one file also changed the name the other four instances, so that's cool.  
All five instances of the LICENSE file still refer to the old name.

**Comment by rgrover** [comment]
No magic here. Renamed license files were in place before this PR. I'd still like for you to think that I'm a magician.

I'll update LICENSE and resubmit

**Comment by rgrover** [comment]
updated LICENSE. @aewp2 please check.

**Comment by aewp2** [comment]
Text looks good.  
There are LICENSE files also inside each target - do you want to keep them?
Amyas

**Comment by rgrover** [comment]
yes, I'd like to keep a copy in the folder where the softdevice resides.

**Comment by rgrover** [comment]
Yes, I'd like to keep the LICENSE files in the module folders. I'll update them as well.

**Comment by rgrover** [comment]
please review: @aewp2

**Comment by aewp2** [comment]
+1 looks good

**Comment by rgrover** [comment]
published.

**Pull request merged**
