### PR TITLE
update gcc linker scripts to provide symbols needed by mbed-alloc.

### PR DESCRIPTION
**Pull request by rgrover**
@autopulated @0xc0170

### CODE REVIEW

**Comment by autopulated** [comment]
Did you change the white space? It's hard to see what actually changed from the diff, but as far as I'm concerned go ahead and merge!

**Comment by rgrover** [comment]
sorry about doing two things within a single commit. Normally I would have made a separate commit for white space.

**Comment by rgrover** [comment]
@autopulated: 'yotta version patch' on each of the component modules doesn't produce appropriate tags. This may be because we've combined modules into a single repo. This this going to be a problem?

**Comment by autopulated** [comment]
Yeah no problem

**Comment by autopulated** [comment]
The tags are only a convenience, publishing will work fine without them. You can create them manually if needed for anything else.

**Pull request merged**
